
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN COMMA DIVIDE ELSE EQ FLOAT GE GT IDENTIFIER IF INT LBRACE LBRACKET LE LPAREN LT MINUS NE NUMBER PLUS PRINT RBRACE RBRACKET RPAREN SEMICOLON TIMES WHILEprogram : statementsstatements : statement statements\n                  | statementstatement : INT IDENTIFIER SEMICOLON\n                 | FLOAT IDENTIFIER SEMICOLONstatement : IDENTIFIER ASSIGN expression SEMICOLONstatement : PRINT LPAREN IDENTIFIER RPAREN SEMICOLONexpression : expression PLUS term\n                  | expression MINUS termexpression : termterm : term TIMES factor\n            | term DIVIDE factorterm : factorfactor : NUMBERfactor : IDENTIFIERfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'INT':([0,3,13,20,22,34,],[4,4,-4,-5,-6,-7,]),'FLOAT':([0,3,13,20,22,34,],[6,6,-4,-5,-6,-7,]),'IDENTIFIER':([0,3,4,6,10,12,13,19,20,22,23,24,25,26,34,],[5,5,9,11,14,21,-4,14,-5,-6,14,14,14,14,-7,]),'PRINT':([0,3,13,20,22,34,],[7,7,-4,-5,-6,-7,]),'$end':([1,2,3,8,13,20,22,34,],[0,-1,-3,-2,-4,-5,-6,-7,]),'ASSIGN':([5,],[10,]),'LPAREN':([7,10,19,23,24,25,26,],[12,19,19,19,19,19,19,]),'SEMICOLON':([9,11,14,15,16,17,18,28,29,30,31,32,33,],[13,20,-15,22,-10,-13,-14,34,-8,-9,-11,-12,-16,]),'NUMBER':([10,19,23,24,25,26,],[18,18,18,18,18,18,]),'TIMES':([14,16,17,18,29,30,31,32,33,],[-15,25,-13,-14,25,25,-11,-12,-16,]),'DIVIDE':([14,16,17,18,29,30,31,32,33,],[-15,26,-13,-14,26,26,-11,-12,-16,]),'PLUS':([14,15,16,17,18,27,29,30,31,32,33,],[-15,23,-10,-13,-14,23,-8,-9,-11,-12,-16,]),'MINUS':([14,15,16,17,18,27,29,30,31,32,33,],[-15,24,-10,-13,-14,24,-8,-9,-11,-12,-16,]),'RPAREN':([14,16,17,18,21,27,29,30,31,32,33,],[-15,-10,-13,-14,28,33,-8,-9,-11,-12,-16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,3,],[2,8,]),'statement':([0,3,],[3,3,]),'expression':([10,19,],[15,27,]),'term':([10,19,23,24,],[16,16,29,30,]),'factor':([10,19,23,24,25,26,],[17,17,17,17,31,32,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','parser.py',18),
  ('statements -> statement statements','statements',2,'p_statements','parser.py',23),
  ('statements -> statement','statements',1,'p_statements','parser.py',24),
  ('statement -> INT IDENTIFIER SEMICOLON','statement',3,'p_statement_decl','parser.py',32),
  ('statement -> FLOAT IDENTIFIER SEMICOLON','statement',3,'p_statement_decl','parser.py',33),
  ('statement -> IDENTIFIER ASSIGN expression SEMICOLON','statement',4,'p_statement_assign','parser.py',38),
  ('statement -> PRINT LPAREN IDENTIFIER RPAREN SEMICOLON','statement',5,'p_statement_print','parser.py',43),
  ('expression -> expression PLUS term','expression',3,'p_expression_binop','parser.py',50),
  ('expression -> expression MINUS term','expression',3,'p_expression_binop','parser.py',51),
  ('expression -> term','expression',1,'p_expression_term','parser.py',56),
  ('term -> term TIMES factor','term',3,'p_term_binop','parser.py',61),
  ('term -> term DIVIDE factor','term',3,'p_term_binop','parser.py',62),
  ('term -> factor','term',1,'p_term_factor','parser.py',67),
  ('factor -> NUMBER','factor',1,'p_factor_num','parser.py',72),
  ('factor -> IDENTIFIER','factor',1,'p_factor_id','parser.py',77),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parser.py',82),
]
